import type { CvarSchemaPack } from '../core/schemaTypes';
import { parseSchemaText } from '../core/schemaLoader';
import { parseJsonCvarDump } from './jsonCvarDumpParser';
import { parseDumpConsoleCommandsText } from './dumpConsoleCommandsTextParser';
import { parseUnrealHelpText } from './unrealHelpTextParser';
import { parseFallbackLines } from './fallbackLineParser';

export interface ImportOptions {
  id: string;
  displayName: string;
  sourcePath?: string;
  game?: string | null;
  gameBuild?: string | null;
}

export function importCvarDumpText(text: string, options: ImportOptions): CvarSchemaPack {
  const existing = parseSchemaText(text);
  if (existing.ok && existing.pack) {
    return existing.pack;
  }

  const parsers = [parseJsonCvarDump, parseDumpConsoleCommandsText, parseUnrealHelpText, parseFallbackLines];
  for (const parser of parsers) {
    const cvars = parser(text);
    if (Object.keys(cvars).length > 0) {
      return {
        schemaVersion: 1,
        id: options.id,
        displayName: options.displayName,
        target: {
          engine: 'Unreal Engine',
          game: options.game ?? null,
          gameBuild: options.gameBuild ?? null
        },
        generatedFrom: {
          source: options.sourcePath ?? 'imported dump',
          generatedAt: new Date().toISOString()
        },
        cvars
      };
    }
  }

  return {
    schemaVersion: 1,
    id: options.id,
    displayName: options.displayName,
    target: { engine: 'Unreal Engine', game: options.game ?? null, gameBuild: options.gameBuild ?? null },
    generatedFrom: { source: options.sourcePath ?? 'empty import', generatedAt: new Date().toISOString() },
    cvars: {}
  };
}

export function toJsonc(pack: CvarSchemaPack): string {
  return [
    '// Generated by INI Tweak Lab. Review imported help/default/current fields before relying on them.',
    JSON.stringify(pack, null, 2)
  ].join('\n');
}
