; Open this file as language mode "INI Tweak" to try hovers, diagnostics, completions, and inlay hints.

[/Script/Engine.RendererSettings]
r.DynamicGlobalIlluminationMethod=1
r.ReflectionMethod=2
r.Shadow.Virtual.Enable=true
r.DynamicGlobalIluminationMethod=1 ; typo: missing one "l"

[SystemSettings]
sg.TextureQuality=4
r.ReflectionMethod=2
r.ReflectionMethod=1 ; duplicate with conflicting value

bad line without equals
